package org.apache.jetspeed.om.apps.email;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jun 10 23:17:32 JST 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class EmailInboxPeer
    extends org.apache.jetspeed.om.apps.email.BaseEmailInboxPeer
{
}
