/*
 * Copyright 2000-2001,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jetspeed.om.apps.email;

import org.apache.commons.lang.ObjectUtils;

import org.apache.torque.om.Persistent;

/** 
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Mar 10 18:18:45 PST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 * 
 * @author <a href="mailto:taylor@apache.org">David Sean Taylor</a>
 * @version $Id: EmailInbox.java,v 1.1 2004/03/11 18:32:05 taylor Exp $
 * 
 */
public  class EmailInbox 
    extends org.apache.jetspeed.om.apps.email.BaseEmailInbox
    implements Persistent
{
    /**
     * The value for the attachment field
     */
    private byte[] attachment;
    
    /**
     * Get the Attachment
     *
     * @return byte[]
     */
    public byte[] getAttachment()
    {
        return attachment;
    }

                                        
    /**
     * Set the value of Attachment
     *
     * @param v new value
     */
    public void setAttachment(byte[] v) 
    {     
        if (!ObjectUtils.equals(this.attachment, v))
        {
            this.attachment = v;
            setModified(true);
        }
    }

    
    
}
