package com.aimluck.eip.cayenne.om.account.auto;

import java.util.List;

/** Class _EipTAclRole was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTAclRole extends org.apache.cayenne.CayenneDataObject {

    public static final String ACL_TYPE_PROPERTY = "aclType";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String FEATURE_ID_PROPERTY = "featureId";
    public static final String NOTE_PROPERTY = "note";
    public static final String ROLE_NAME_PROPERTY = "roleName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TACL_PORTLET_FEATURE_PROPERTY = "eipTAclPortletFeature";
    public static final String EIP_TACL_USER_ROLE_MAPS_PROPERTY = "eipTAclUserRoleMaps";

    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setAclType(Integer aclType) {
        writeProperty("aclType", aclType);
    }
    public Integer getAclType() {
        return (Integer)readProperty("aclType");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setFeatureId(Integer featureId) {
        writeProperty("featureId", featureId);
    }
    public Integer getFeatureId() {
        return (Integer)readProperty("featureId");
    }
    
    
    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }
    
    
    public void setRoleName(String roleName) {
        writeProperty("roleName", roleName);
    }
    public String getRoleName() {
        return (String)readProperty("roleName");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setEipTAclPortletFeature(com.aimluck.eip.cayenne.om.account.EipTAclPortletFeature eipTAclPortletFeature) {
        setToOneTarget("eipTAclPortletFeature", eipTAclPortletFeature, true);
    }

    public com.aimluck.eip.cayenne.om.account.EipTAclPortletFeature getEipTAclPortletFeature() {
        return (com.aimluck.eip.cayenne.om.account.EipTAclPortletFeature)readProperty("eipTAclPortletFeature");
    } 
    
    
    public void addToEipTAclUserRoleMaps(com.aimluck.eip.cayenne.om.account.EipTAclUserRoleMap obj) {
        addToManyTarget("eipTAclUserRoleMaps", obj, true);
    }
    public void removeFromEipTAclUserRoleMaps(com.aimluck.eip.cayenne.om.account.EipTAclUserRoleMap obj) {
        removeToManyTarget("eipTAclUserRoleMaps", obj, true);
    }
    public List getEipTAclUserRoleMaps() {
        return (List)readProperty("eipTAclUserRoleMaps");
    }
    
    
}
