package com.aimluck.eip.cayenne.om.account.auto;

/** Class _VEipMUserGroupList was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _VEipMUserGroupList extends org.apache.cayenne.CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String POS_PROPERTY = "pos";
    public static final String SORT_PROPERTY = "sort";
    public static final String TYPE_PROPERTY = "type";

    public static final String UID_PK_COLUMN = "UID";

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setPos(Integer pos) {
        writeProperty("pos", pos);
    }
    public Integer getPos() {
        return (Integer)readProperty("pos");
    }
    
    
    public void setSort(Integer sort) {
        writeProperty("sort", sort);
    }
    public Integer getSort() {
        return (Integer)readProperty("sort");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
}
