package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTCabinetFolder was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTCabinetFolder extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String CREATE_USER_ID_PROPERTY = "createUserId";
    public static final String FOLDER_NAME_PROPERTY = "folderName";
    public static final String NOTE_PROPERTY = "note";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String EIP_TCABINET_FILES_PROPERTY = "eipTCabinetFiles";
    public static final String EIP_TCABINET_FOLDER_MAP_PROPERTY = "eipTCabinetFolderMap";

    public static final String FOLDER_ID_PK_COLUMN = "FOLDER_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setCreateUserId(Integer createUserId) {
        writeProperty("createUserId", createUserId);
    }
    public Integer getCreateUserId() {
        return (Integer)readProperty("createUserId");
    }
    
    
    public void setFolderName(String folderName) {
        writeProperty("folderName", folderName);
    }
    public String getFolderName() {
        return (String)readProperty("folderName");
    }
    
    
    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }
    
    
    public void setParentId(Integer parentId) {
        writeProperty("parentId", parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty("parentId");
    }
    
    
    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }
    
    
    public void addToEipTCabinetFiles(com.aimluck.eip.cayenne.om.portlet.EipTCabinetFile obj) {
        addToManyTarget("eipTCabinetFiles", obj, true);
    }
    public void removeFromEipTCabinetFiles(com.aimluck.eip.cayenne.om.portlet.EipTCabinetFile obj) {
        removeToManyTarget("eipTCabinetFiles", obj, true);
    }
    public List getEipTCabinetFiles() {
        return (List)readProperty("eipTCabinetFiles");
    }
    
    
    public void addToEipTCabinetFolderMap(com.aimluck.eip.cayenne.om.portlet.EipTCabinetFolderMap obj) {
        addToManyTarget("eipTCabinetFolderMap", obj, true);
    }
    public void removeFromEipTCabinetFolderMap(com.aimluck.eip.cayenne.om.portlet.EipTCabinetFolderMap obj) {
        removeToManyTarget("eipTCabinetFolderMap", obj, true);
    }
    public List getEipTCabinetFolderMap() {
        return (List)readProperty("eipTCabinetFolderMap");
    }
    
    
}
