package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTWorkflowRequestMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTWorkflowRequestMap extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NOTE_PROPERTY = "note";
    public static final String ORDER_INDEX_PROPERTY = "orderIndex";
    public static final String STATUS_PROPERTY = "status";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TWORKFLOW_REQUEST_PROPERTY = "eipTWorkflowRequest";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }
    
    
    public void setOrderIndex(Integer orderIndex) {
        writeProperty("orderIndex", orderIndex);
    }
    public Integer getOrderIndex() {
        return (Integer)readProperty("orderIndex");
    }
    
    
    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void setEipTWorkflowRequest(com.aimluck.eip.cayenne.om.portlet.EipTWorkflowRequest eipTWorkflowRequest) {
        setToOneTarget("eipTWorkflowRequest", eipTWorkflowRequest, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTWorkflowRequest getEipTWorkflowRequest() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTWorkflowRequest)readProperty("eipTWorkflowRequest");
    } 
    
    
}
