package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTMailFolder was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMailFolder extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String FOLDER_NAME_PROPERTY = "folderName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_MMAIL_ACCOUNT_PROPERTY = "eipMMailAccount";

    public static final String FOLDER_ID_PK_COLUMN = "FOLDER_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setFolderName(String folderName) {
        writeProperty("folderName", folderName);
    }
    public String getFolderName() {
        return (String)readProperty("folderName");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setEipMMailAccount(com.aimluck.eip.cayenne.om.portlet.EipMMailAccount eipMMailAccount) {
        setToOneTarget("eipMMailAccount", eipMMailAccount, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipMMailAccount getEipMMailAccount() {
        return (com.aimluck.eip.cayenne.om.portlet.EipMMailAccount)readProperty("eipMMailAccount");
    } 
    
    
}
