package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTMsgboardTopic was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMsgboardTopic extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String CREATE_USER_ID_PROPERTY = "createUserId";
    public static final String NOTE_PROPERTY = "note";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String TOPIC_NAME_PROPERTY = "topicName";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String UPDATE_USER_ID_PROPERTY = "updateUserId";
    public static final String EIP_TMSGBOARD_CATEGORY_PROPERTY = "eipTMsgboardCategory";
    public static final String EIP_TMSGBOARD_FILE_ARRAY_PROPERTY = "eipTMsgboardFileArray";

    public static final String TOPIC_ID_PK_COLUMN = "TOPIC_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setCreateUserId(Integer createUserId) {
        writeProperty("createUserId", createUserId);
    }
    public Integer getCreateUserId() {
        return (Integer)readProperty("createUserId");
    }
    
    
    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }
    
    
    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }
    
    
    public void setParentId(Integer parentId) {
        writeProperty("parentId", parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty("parentId");
    }
    
    
    public void setTopicName(String topicName) {
        writeProperty("topicName", topicName);
    }
    public String getTopicName() {
        return (String)readProperty("topicName");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUpdateUserId(Integer updateUserId) {
        writeProperty("updateUserId", updateUserId);
    }
    public Integer getUpdateUserId() {
        return (Integer)readProperty("updateUserId");
    }
    
    
    public void setEipTMsgboardCategory(com.aimluck.eip.cayenne.om.portlet.EipTMsgboardCategory eipTMsgboardCategory) {
        setToOneTarget("eipTMsgboardCategory", eipTMsgboardCategory, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTMsgboardCategory getEipTMsgboardCategory() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTMsgboardCategory)readProperty("eipTMsgboardCategory");
    } 
    
    
    public void addToEipTMsgboardFileArray(com.aimluck.eip.cayenne.om.portlet.EipTMsgboardFile obj) {
        addToManyTarget("eipTMsgboardFileArray", obj, true);
    }
    public void removeFromEipTMsgboardFileArray(com.aimluck.eip.cayenne.om.portlet.EipTMsgboardFile obj) {
        removeToManyTarget("eipTMsgboardFileArray", obj, true);
    }
    public List getEipTMsgboardFileArray() {
        return (List)readProperty("eipTMsgboardFileArray");
    }
    
    
}
