package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTTimelineUrl was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTTimelineUrl extends org.apache.cayenne.CayenneDataObject {

    public static final String BODY_PROPERTY = "body";
    public static final String THUMBNAIL_PROPERTY = "thumbnail";
    public static final String TIMELINE_ID_PROPERTY = "timelineId";
    public static final String TITLE_PROPERTY = "title";
    public static final String URL_PROPERTY = "url";
    public static final String EIP_TTIMELINE_PROPERTY = "eipTTimeline";

    public static final String URL_ID_PK_COLUMN = "URL_ID";

    public void setBody(String body) {
        writeProperty("body", body);
    }
    public String getBody() {
        return (String)readProperty("body");
    }
    
    
    public void setThumbnail(byte[] thumbnail) {
        writeProperty("thumbnail", thumbnail);
    }
    public byte[] getThumbnail() {
        return (byte[])readProperty("thumbnail");
    }
    
    
    public void setTimelineId(Integer timelineId) {
        writeProperty("timelineId", timelineId);
    }
    public Integer getTimelineId() {
        return (Integer)readProperty("timelineId");
    }
    
    
    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }
    
    
    public void setEipTTimeline(com.aimluck.eip.cayenne.om.portlet.EipTTimeline eipTTimeline) {
        setToOneTarget("eipTTimeline", eipTTimeline, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTTimeline getEipTTimeline() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTTimeline)readProperty("eipTTimeline");
    } 
    
    
}
