package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTMsgboardCategoryMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTMsgboardCategoryMap extends org.apache.cayenne.CayenneDataObject {

    public static final String CATEGORY_ID_PROPERTY = "categoryId";
    public static final String STATUS_PROPERTY = "status";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TMSGBOARD_CATEGORY_PROPERTY = "eipTMsgboardCategory";

    public static final String ID_PK_COLUMN = "ID";

    public void setCategoryId(Integer categoryId) {
        writeProperty("categoryId", categoryId);
    }
    public Integer getCategoryId() {
        return (Integer)readProperty("categoryId");
    }
    
    
    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void setEipTMsgboardCategory(com.aimluck.eip.cayenne.om.portlet.EipTMsgboardCategory eipTMsgboardCategory) {
        setToOneTarget("eipTMsgboardCategory", eipTMsgboardCategory, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTMsgboardCategory getEipTMsgboardCategory() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTMsgboardCategory)readProperty("eipTMsgboardCategory");
    } 
    
    
}
