package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTBlogFootmarkMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTBlogFootmarkMap extends org.apache.cayenne.CayenneDataObject {

    public static final String BLOG_ID_PROPERTY = "blogId";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String EIP_TBLOG_PROPERTY = "eipTBlog";

    public static final String ID_PK_COLUMN = "ID";

    public void setBlogId(Integer blogId) {
        writeProperty("blogId", blogId);
    }
    public Integer getBlogId() {
        return (Integer)readProperty("blogId");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }
    
    
    public void setEipTBlog(com.aimluck.eip.cayenne.om.portlet.EipTBlog eipTBlog) {
        setToOneTarget("eipTBlog", eipTBlog, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTBlog getEipTBlog() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTBlog)readProperty("eipTBlog");
    } 
    
    
}
