package com.aimluck.eip.cayenne.om.portlet.auto;

/** Class _EipTTimelineMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTTimelineMap extends org.apache.cayenne.CayenneDataObject {

    public static final String IS_READ_PROPERTY = "isRead";
    public static final String LOGIN_NAME_PROPERTY = "loginName";
    public static final String EIP_TTIMELINE_PROPERTY = "eipTTimeline";

    public static final String ID_PK_COLUMN = "ID";

    public void setIsRead(Integer isRead) {
        writeProperty("isRead", isRead);
    }
    public Integer getIsRead() {
        return (Integer)readProperty("isRead");
    }
    
    
    public void setLoginName(String loginName) {
        writeProperty("loginName", loginName);
    }
    public String getLoginName() {
        return (String)readProperty("loginName");
    }
    
    
    public void setEipTTimeline(com.aimluck.eip.cayenne.om.portlet.EipTTimeline eipTTimeline) {
        setToOneTarget("eipTTimeline", eipTTimeline, true);
    }

    public com.aimluck.eip.cayenne.om.portlet.EipTTimeline getEipTTimeline() {
        return (com.aimluck.eip.cayenne.om.portlet.EipTTimeline)readProperty("eipTTimeline");
    } 
    
    
}
