package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTTimeline was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTTimeline extends org.apache.cayenne.CayenneDataObject {

    public static final String APP_ID_PROPERTY = "appId";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String EXTERNAL_ID_PROPERTY = "externalId";
    public static final String NOTE_PROPERTY = "note";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String PARAMS_PROPERTY = "params";
    public static final String PARENT_ID_PROPERTY = "parentId";
    public static final String TIMELINE_TYPE_PROPERTY = "timelineType";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TTIMELINE_FILE_PROPERTY = "eipTTimelineFile";
    public static final String EIP_TTIMELINE_LIKE_PROPERTY = "eipTTimelineLike";
    public static final String TURBINE_USER_PROPERTY = "turbineUser";

    public static final String TIMELINE_ID_PK_COLUMN = "TIMELINE_ID";

    public void setAppId(String appId) {
        writeProperty("appId", appId);
    }
    public String getAppId() {
        return (String)readProperty("appId");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setExternalId(String externalId) {
        writeProperty("externalId", externalId);
    }
    public String getExternalId() {
        return (String)readProperty("externalId");
    }
    
    
    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }
    
    
    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }
    
    
    public void setParams(String params) {
        writeProperty("params", params);
    }
    public String getParams() {
        return (String)readProperty("params");
    }
    
    
    public void setParentId(Integer parentId) {
        writeProperty("parentId", parentId);
    }
    public Integer getParentId() {
        return (Integer)readProperty("parentId");
    }
    
    
    public void setTimelineType(String timelineType) {
        writeProperty("timelineType", timelineType);
    }
    public String getTimelineType() {
        return (String)readProperty("timelineType");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void addToEipTTimelineFile(com.aimluck.eip.cayenne.om.portlet.EipTTimelineFile obj) {
        addToManyTarget("eipTTimelineFile", obj, true);
    }
    public void removeFromEipTTimelineFile(com.aimluck.eip.cayenne.om.portlet.EipTTimelineFile obj) {
        removeToManyTarget("eipTTimelineFile", obj, true);
    }
    public List getEipTTimelineFile() {
        return (List)readProperty("eipTTimelineFile");
    }
    
    
    public void addToEipTTimelineLike(com.aimluck.eip.cayenne.om.portlet.EipTTimelineLike obj) {
        addToManyTarget("eipTTimelineLike", obj, true);
    }
    public void removeFromEipTTimelineLike(com.aimluck.eip.cayenne.om.portlet.EipTTimelineLike obj) {
        removeToManyTarget("eipTTimelineLike", obj, true);
    }
    public List getEipTTimelineLike() {
        return (List)readProperty("eipTTimelineLike");
    }
    
    
    public void setTurbineUser(com.aimluck.eip.cayenne.om.security.TurbineUser turbineUser) {
        setToOneTarget("turbineUser", turbineUser, true);
    }

    public com.aimluck.eip.cayenne.om.security.TurbineUser getTurbineUser() {
        return (com.aimluck.eip.cayenne.om.security.TurbineUser)readProperty("turbineUser");
    } 
    
    
}
