package com.aimluck.eip.cayenne.om.portlet.auto;

import java.util.List;

/** Class _EipTBlog was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _EipTBlog extends org.apache.cayenne.CayenneDataObject {

    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String EIP_TBLOG_ENTRYS_PROPERTY = "eipTBlogEntrys";
    public static final String EIP_TBLOG_FOOTMARK_MAPS_PROPERTY = "eipTBlogFootmarkMaps";

    public static final String BLOG_ID_PK_COLUMN = "BLOG_ID";

    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void addToEipTBlogEntrys(com.aimluck.eip.cayenne.om.portlet.EipTBlogEntry obj) {
        addToManyTarget("eipTBlogEntrys", obj, true);
    }
    public void removeFromEipTBlogEntrys(com.aimluck.eip.cayenne.om.portlet.EipTBlogEntry obj) {
        removeToManyTarget("eipTBlogEntrys", obj, true);
    }
    public List getEipTBlogEntrys() {
        return (List)readProperty("eipTBlogEntrys");
    }
    
    
    public void addToEipTBlogFootmarkMaps(com.aimluck.eip.cayenne.om.portlet.EipTBlogFootmarkMap obj) {
        addToManyTarget("eipTBlogFootmarkMaps", obj, true);
    }
    public void removeFromEipTBlogFootmarkMaps(com.aimluck.eip.cayenne.om.portlet.EipTBlogFootmarkMap obj) {
        removeToManyTarget("eipTBlogFootmarkMaps", obj, true);
    }
    public List getEipTBlogFootmarkMaps() {
        return (List)readProperty("eipTBlogFootmarkMaps");
    }
    
    
}
