package com.aimluck.eip.cayenne.om.security.auto;

import java.util.List;

/** Class _TurbineGroup was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineGroup extends org.apache.cayenne.CayenneDataObject {

    public static final String GROUP_ALIAS_NAME_PROPERTY = "groupAliasName";
    public static final String GROUP_NAME_PROPERTY = "groupName";
    public static final String OBJECTDATA_PROPERTY = "objectdata";
    public static final String OWNER_ID_PROPERTY = "ownerId";
    public static final String PUBLIC_FLAG_PROPERTY = "publicFlag";
    public static final String EIP_FACILITY_GROUP_PROPERTY = "eipFacilityGroup";
    public static final String EIP_MPOST_PROPERTY = "eipMPost";
    public static final String TURBINE_USER_GROUP_ROLE_PROPERTY = "turbineUserGroupRole";

    public static final String GROUP_ID_PK_COLUMN = "GROUP_ID";

    public void setGroupAliasName(String groupAliasName) {
        writeProperty("groupAliasName", groupAliasName);
    }
    public String getGroupAliasName() {
        return (String)readProperty("groupAliasName");
    }
    
    
    public void setGroupName(String groupName) {
        writeProperty("groupName", groupName);
    }
    public String getGroupName() {
        return (String)readProperty("groupName");
    }
    
    
    public void setObjectdata(byte[] objectdata) {
        writeProperty("objectdata", objectdata);
    }
    public byte[] getObjectdata() {
        return (byte[])readProperty("objectdata");
    }
    
    
    public void setOwnerId(Integer ownerId) {
        writeProperty("ownerId", ownerId);
    }
    public Integer getOwnerId() {
        return (Integer)readProperty("ownerId");
    }
    
    
    public void setPublicFlag(String publicFlag) {
        writeProperty("publicFlag", publicFlag);
    }
    public String getPublicFlag() {
        return (String)readProperty("publicFlag");
    }
    
    
    public void addToEipFacilityGroup(com.aimluck.eip.cayenne.om.portlet.EipFacilityGroup obj) {
        addToManyTarget("eipFacilityGroup", obj, true);
    }
    public void removeFromEipFacilityGroup(com.aimluck.eip.cayenne.om.portlet.EipFacilityGroup obj) {
        removeToManyTarget("eipFacilityGroup", obj, true);
    }
    public List getEipFacilityGroup() {
        return (List)readProperty("eipFacilityGroup");
    }
    
    
    public void setEipMPost(com.aimluck.eip.cayenne.om.account.EipMPost eipMPost) {
        setToOneTarget("eipMPost", eipMPost, true);
    }

    public com.aimluck.eip.cayenne.om.account.EipMPost getEipMPost() {
        return (com.aimluck.eip.cayenne.om.account.EipMPost)readProperty("eipMPost");
    } 
    
    
    public void addToTurbineUserGroupRole(com.aimluck.eip.cayenne.om.security.TurbineUserGroupRole obj) {
        addToManyTarget("turbineUserGroupRole", obj, true);
    }
    public void removeFromTurbineUserGroupRole(com.aimluck.eip.cayenne.om.security.TurbineUserGroupRole obj) {
        removeToManyTarget("turbineUserGroupRole", obj, true);
    }
    public List getTurbineUserGroupRole() {
        return (List)readProperty("turbineUserGroupRole");
    }
    
    
}
