package com.aimluck.eip.cayenne.om.security.auto;

import java.util.List;

/** Class _TurbineRole was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _TurbineRole extends org.apache.cayenne.CayenneDataObject {

    public static final String OBJECTDATA_PROPERTY = "objectdata";
    public static final String ROLE_NAME_PROPERTY = "roleName";
    public static final String TURBINE_ROLE_PERMISSION_PROPERTY = "turbineRolePermission";
    public static final String TURBINE_USER_GROUP_ROLE_PROPERTY = "turbineUserGroupRole";

    public static final String ROLE_ID_PK_COLUMN = "ROLE_ID";

    public void setObjectdata(byte[] objectdata) {
        writeProperty("objectdata", objectdata);
    }
    public byte[] getObjectdata() {
        return (byte[])readProperty("objectdata");
    }
    
    
    public void setRoleName(String roleName) {
        writeProperty("roleName", roleName);
    }
    public String getRoleName() {
        return (String)readProperty("roleName");
    }
    
    
    public void addToTurbineRolePermission(com.aimluck.eip.cayenne.om.security.TurbineRolePermission obj) {
        addToManyTarget("turbineRolePermission", obj, true);
    }
    public void removeFromTurbineRolePermission(com.aimluck.eip.cayenne.om.security.TurbineRolePermission obj) {
        removeToManyTarget("turbineRolePermission", obj, true);
    }
    public List getTurbineRolePermission() {
        return (List)readProperty("turbineRolePermission");
    }
    
    
    public void addToTurbineUserGroupRole(com.aimluck.eip.cayenne.om.security.TurbineUserGroupRole obj) {
        addToManyTarget("turbineUserGroupRole", obj, true);
    }
    public void removeFromTurbineUserGroupRole(com.aimluck.eip.cayenne.om.security.TurbineUserGroupRole obj) {
        removeToManyTarget("turbineUserGroupRole", obj, true);
    }
    public List getTurbineUserGroupRole() {
        return (List)readProperty("turbineUserGroupRole");
    }
    
    
}
