

package org.apache.jetspeed.om.security.turbine;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.om.Persistent;

/**
 * This class manages TurbineGroup objects.
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jun 10 23:17:32 JST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class TurbineGroupManager
    extends BaseTurbineGroupManager
{
    /**
     * Creates a new <code>TurbineGroupManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public TurbineGroupManager()
        throws TorqueException
    {
        super();
    }
}
