-- 20130124
UPDATE EIP_T_ACL_PORTLET_FEATURE SET FEATURE_ALIAS_NAME = 'ユーザー名簿操作' WHERE FEATURE_NAME = 'addressbook_address_inside' AND FEATURE_ALIAS_NAME = 'アドレス帳（社内アドレス）操作';
UPDATE EIP_T_ACL_ROLE SET ROLE_NAME = 'ユーザー名簿管理者' WHERE  FEATURE_ID IN (SELECT FEATURE_ID FROM EIP_T_ACL_PORTLET_FEATURE WHERE FEATURE_NAME = 'addressbook_address_inside') AND ROLE_NAME = 'アドレス帳（社内アドレス）管理者';
-- 20130124