package com.aimluck.eip.cayenne.om.social.auto;

/** Class _ActivityMap was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _ActivityMap extends org.apache.cayenne.CayenneDataObject {

    public static final String IS_READ_PROPERTY = "isRead";
    public static final String LOGIN_NAME_PROPERTY = "loginName";
    public static final String ACTIVITY_PROPERTY = "activity";

    public static final String ID_PK_COLUMN = "ID";

    public void setIsRead(Integer isRead) {
        writeProperty("isRead", isRead);
    }
    public Integer getIsRead() {
        return (Integer)readProperty("isRead");
    }
    
    
    public void setLoginName(String loginName) {
        writeProperty("loginName", loginName);
    }
    public String getLoginName() {
        return (String)readProperty("loginName");
    }
    
    
    public void setActivity(com.aimluck.eip.cayenne.om.social.Activity activity) {
        setToOneTarget("activity", activity, true);
    }

    public com.aimluck.eip.cayenne.om.social.Activity getActivity() {
        return (com.aimluck.eip.cayenne.om.social.Activity)readProperty("activity");
    } 
    
    
}
