package com.aimluck.eip.cayenne.om.social.auto;

/** Class _OAuthConsumer was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _OAuthConsumer extends org.apache.cayenne.CayenneDataObject {

    public static final String CONSUMER_KEY_PROPERTY = "consumerKey";
    public static final String CONSUMER_SECRET_PROPERTY = "consumerSecret";
    public static final String CREATE_DATE_PROPERTY = "createDate";
    public static final String NAME_PROPERTY = "name";
    public static final String TYPE_PROPERTY = "type";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String APPLICATION_PROPERTY = "application";

    public static final String ID_PK_COLUMN = "ID";

    public void setConsumerKey(String consumerKey) {
        writeProperty("consumerKey", consumerKey);
    }
    public String getConsumerKey() {
        return (String)readProperty("consumerKey");
    }
    
    
    public void setConsumerSecret(String consumerSecret) {
        writeProperty("consumerSecret", consumerSecret);
    }
    public String getConsumerSecret() {
        return (String)readProperty("consumerSecret");
    }
    
    
    public void setCreateDate(java.util.Date createDate) {
        writeProperty("createDate", createDate);
    }
    public java.util.Date getCreateDate() {
        return (java.util.Date)readProperty("createDate");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
    public void setUpdateDate(java.util.Date updateDate) {
        writeProperty("updateDate", updateDate);
    }
    public java.util.Date getUpdateDate() {
        return (java.util.Date)readProperty("updateDate");
    }
    
    
    public void setApplication(com.aimluck.eip.cayenne.om.social.Application application) {
        setToOneTarget("application", application, true);
    }

    public com.aimluck.eip.cayenne.om.social.Application getApplication() {
        return (com.aimluck.eip.cayenne.om.social.Application)readProperty("application");
    } 
    
    
}
