package com.aimluck.eip.cayenne.om.social.auto;

/** Class _OAuthEntry was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _OAuthEntry extends org.apache.cayenne.CayenneDataObject {

    public static final String APP_ID_PROPERTY = "appId";
    public static final String AUTHORIZED_PROPERTY = "authorized";
    public static final String CALLBACK_TOKEN_PROPERTY = "callbackToken";
    public static final String CALLBACK_TOKEN_ATTEMPTS_PROPERTY = "callbackTokenAttempts";
    public static final String CALLBACK_URL_PROPERTY = "callbackUrl";
    public static final String CALLBACK_URL_SIGNED_PROPERTY = "callbackUrlSigned";
    public static final String CONSUMER_KEY_PROPERTY = "consumerKey";
    public static final String CONTAINER_PROPERTY = "container";
    public static final String DOMAIN_PROPERTY = "domain";
    public static final String ISSUE_TIME_PROPERTY = "issueTime";
    public static final String OAUTH_VERSION_PROPERTY = "oauthVersion";
    public static final String TOKEN_PROPERTY = "token";
    public static final String TOKEN_SECRET_PROPERTY = "tokenSecret";
    public static final String TYPE_PROPERTY = "type";
    public static final String USER_ID_PROPERTY = "userId";

    public static final String ID_PK_COLUMN = "ID";

    public void setAppId(String appId) {
        writeProperty("appId", appId);
    }
    public String getAppId() {
        return (String)readProperty("appId");
    }
    
    
    public void setAuthorized(Integer authorized) {
        writeProperty("authorized", authorized);
    }
    public Integer getAuthorized() {
        return (Integer)readProperty("authorized");
    }
    
    
    public void setCallbackToken(String callbackToken) {
        writeProperty("callbackToken", callbackToken);
    }
    public String getCallbackToken() {
        return (String)readProperty("callbackToken");
    }
    
    
    public void setCallbackTokenAttempts(Integer callbackTokenAttempts) {
        writeProperty("callbackTokenAttempts", callbackTokenAttempts);
    }
    public Integer getCallbackTokenAttempts() {
        return (Integer)readProperty("callbackTokenAttempts");
    }
    
    
    public void setCallbackUrl(String callbackUrl) {
        writeProperty("callbackUrl", callbackUrl);
    }
    public String getCallbackUrl() {
        return (String)readProperty("callbackUrl");
    }
    
    
    public void setCallbackUrlSigned(Integer callbackUrlSigned) {
        writeProperty("callbackUrlSigned", callbackUrlSigned);
    }
    public Integer getCallbackUrlSigned() {
        return (Integer)readProperty("callbackUrlSigned");
    }
    
    
    public void setConsumerKey(String consumerKey) {
        writeProperty("consumerKey", consumerKey);
    }
    public String getConsumerKey() {
        return (String)readProperty("consumerKey");
    }
    
    
    public void setContainer(String container) {
        writeProperty("container", container);
    }
    public String getContainer() {
        return (String)readProperty("container");
    }
    
    
    public void setDomain(String domain) {
        writeProperty("domain", domain);
    }
    public String getDomain() {
        return (String)readProperty("domain");
    }
    
    
    public void setIssueTime(java.util.Date issueTime) {
        writeProperty("issueTime", issueTime);
    }
    public java.util.Date getIssueTime() {
        return (java.util.Date)readProperty("issueTime");
    }
    
    
    public void setOauthVersion(String oauthVersion) {
        writeProperty("oauthVersion", oauthVersion);
    }
    public String getOauthVersion() {
        return (String)readProperty("oauthVersion");
    }
    
    
    public void setToken(String token) {
        writeProperty("token", token);
    }
    public String getToken() {
        return (String)readProperty("token");
    }
    
    
    public void setTokenSecret(String tokenSecret) {
        writeProperty("tokenSecret", tokenSecret);
    }
    public String getTokenSecret() {
        return (String)readProperty("tokenSecret");
    }
    
    
    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }
    
    
    public void setUserId(String userId) {
        writeProperty("userId", userId);
    }
    public String getUserId() {
        return (String)readProperty("userId");
    }
    
    
}
