/*
 * Copyright 2000-2001,2004 The Apache Software Foundation.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.jetspeed.util.types;


/**

Autogenerated JavaBean from xjay (http://relativity.yi.org/xjay)

@author XJay
@version $Id: Parameter.java,v 1.4 2004/02/23 03:17:30 jford Exp $
*/


public class Parameter {

    

    //BEGIN members
    
    private String _name;
    
    private String _value;
    
    private String _type;
    
    //END members

    //BEGIN methods
    
    public String getName() {
        return this._name;
    }
                        
        
    public void setName ( String _name ) {
        this._name = _name;
    }
    
    public String getValue() {
        return this._value;
    }
                        
        
    public void setValue ( String _value ) {
        this._value = _value;
    }
    
    public String getType() {
        return this._type;
    }
                        
        
    public void setType ( String _type ) {
        this._type = _type;
    }
    
    //END methods    
}